import type { WatchItem } from './types';

export const DEFAULT_WATCH_ITEMS: WatchItem[] = [
  {
    id: 'theme-hk-internet-tech',
    kind: 'theme',
    displayName: '港股互联网 / 科技',
    metricMode: 'valuation',
    enabled: true,
    sourceHoldings: ['513050', '159202', '513180'],
    preferredMetrics: ['pe'],
    proxyName: '恒生工商指数',
    focusCodes: ['513050', '159202', '513180'],
    note: '使用恒生工商指数 PE 作为港股互联网 / 科技暴露的公开代理。',
    sources: [
      {
        kind: 'legulegu_html_table',
        pageUrl: 'https://legulegu.com/stockdata/market/hsci',
        columns: { pe: '市盈率' },
      },
    ],
  },
  {
    id: 'theme-hk-broad',
    kind: 'theme',
    displayName: '港股宽基',
    metricMode: 'valuation',
    enabled: true,
    sourceHoldings: ['159920'],
    preferredMetrics: ['pe'],
    proxyName: '恒生指数',
    focusCodes: ['159920'],
    note: '恒生指数公开数据当前仅稳定提供 PE。',
    sources: [
      {
        kind: 'legulegu_html_table',
        pageUrl: 'https://legulegu.com/stockdata/market/hsi',
        columns: { pe: '市盈率' },
      },
    ],
  },
  {
    id: 'theme-health-biotech',
    kind: 'theme',
    displayName: '医药 / 创新药 / 生物科技',
    metricMode: 'valuation',
    enabled: true,
    sourceHoldings: ['520500', '159502', '159938'],
    preferredMetrics: ['pe', 'pb'],
    proxyName: '中证医药',
    focusCodes: ['520500', '159502', '159938'],
    sources: [{ kind: 'legulegu_index_basic', indexCode: '000933.SH' }],
  },
  {
    id: 'theme-semiconductor',
    kind: 'theme',
    displayName: '半导体 / 芯片',
    metricMode: 'valuation',
    enabled: true,
    sourceHoldings: ['513310'],
    preferredMetrics: ['pe', 'pb'],
    proxyName: '中证半导全收益',
    focusCodes: ['513310'],
    sources: [{ kind: 'legulegu_index_basic', indexCode: 'h21081.CSI' }],
  },
  {
    id: 'theme-dividend',
    kind: 'theme',
    displayName: '红利 / 高股息',
    metricMode: 'valuation',
    enabled: true,
    sourceHoldings: ['159525'],
    preferredMetrics: ['pe', 'pb'],
    proxyName: '中证红利低波',
    focusCodes: ['159525'],
    sources: [{ kind: 'legulegu_index_basic', indexCode: 'h30269.CSI' }],
  },
  {
    id: 'theme-a-large-cap',
    kind: 'theme',
    displayName: 'A股大盘蓝筹',
    metricMode: 'valuation',
    enabled: true,
    sourceHoldings: ['510050'],
    preferredMetrics: ['pe', 'pb'],
    proxyName: '上证50',
    focusCodes: ['510050'],
    sources: [{ kind: 'legulegu_index_basic', indexCode: '000016.SH' }],
  },
  {
    id: 'theme-a-mid-cap',
    kind: 'theme',
    displayName: 'A股中盘',
    metricMode: 'valuation',
    enabled: true,
    sourceHoldings: ['510580'],
    preferredMetrics: ['pe', 'pb'],
    proxyName: '中证500',
    focusCodes: ['510580'],
    sources: [{ kind: 'legulegu_index_basic', indexCode: '000905.SH' }],
  },
  {
    id: 'theme-sci-tech-growth',
    kind: 'theme',
    displayName: '科创成长',
    metricMode: 'valuation',
    enabled: true,
    sourceHoldings: ['588000'],
    preferredMetrics: ['pe', 'pb'],
    proxyName: '科创50',
    focusCodes: ['588000'],
    sources: [{ kind: 'legulegu_index_basic', indexCode: '000688.SH' }],
  },
  {
    id: 'theme-chi-next-growth',
    kind: 'theme',
    displayName: '创业板成长',
    metricMode: 'valuation',
    enabled: true,
    sourceHoldings: ['159949'],
    preferredMetrics: ['pe', 'pb'],
    proxyName: '创业板50',
    focusCodes: ['159949'],
    sources: [{ kind: 'legulegu_index_basic', indexCode: '399673.SZ' }],
  },
  {
    id: 'theme-us-tech',
    kind: 'theme',
    displayName: '美股科技',
    metricMode: 'price',
    enabled: true,
    sourceHoldings: ['159659'],
    preferredMetrics: ['price'],
    proxyName: '纳斯达克100指数',
    focusCodes: ['159659'],
    note: '当前无稳定公开的纳斯达克100 PE/PB 五年历史口径，第一版先用价格分位做代理。',
    sources: [
      {
        kind: 'legulegu_aggregation',
        pageUrl: 'https://legulegu.com/stockdata/charts/646',
        requestedDataKeys: ['sp500UsMarketIndex', 'nasdaq100UsMarketIndex'],
        primarySeriesIndex: 1,
      },
    ],
  },
  {
    id: 'theme-us-broad',
    kind: 'theme',
    displayName: '美股宽基',
    metricMode: 'valuation',
    enabled: true,
    sourceHoldings: ['513500'],
    preferredMetrics: ['pe'],
    proxyName: '标普500',
    focusCodes: ['513500'],
    note: '标普500当前稳定公开提供 PE；PB 在公开免费源上不稳定，第一版不强行展示。',
    sources: [
      {
        kind: 'legulegu_aggregation',
        pageUrl: 'https://legulegu.com/stockdata/market/sandp',
        requestedDataKeys: ['sp500UsMarketIndex', 'sp500Pe'],
        primarySeriesIndex: 1,
      },
    ],
  },
  {
    id: 'macro-dxy',
    kind: 'macro',
    displayName: 'DXY',
    metricMode: 'price',
    enabled: true,
    sourceHoldings: [],
    preferredMetrics: ['price'],
    proxyName: '美元指数',
    focusCodes: ['DXY'],
    sources: [
      {
        kind: 'legulegu_aggregation',
        pageUrl: 'https://legulegu.com/stockdata/charts/1075',
        requestedDataKeys: ['us_dollar_index', 'xau_usd'],
        primarySeriesIndex: 0,
      },
    ],
  },
  {
    id: 'macro-usd-cnh',
    kind: 'macro',
    displayName: 'USD/CNH',
    metricMode: 'price',
    enabled: true,
    sourceHoldings: [],
    preferredMetrics: ['price'],
    proxyName: '美元兑离岸人民币',
    focusCodes: ['USD/CNH'],
    note: '优先抓 Yahoo 的 USD/CNH；若失败，则回退到人民币汇率中间价作为近似代理。',
    sources: [
      { kind: 'yahoo_chart', symbol: 'USDCNH=X' },
      {
        kind: 'legulegu_aggregation',
        pageUrl: 'https://legulegu.com/stockdata/chart-builder?chartKeyA=rmb_dollar_exhange_rate&chartKeyB=hs300',
        requestedDataKeys: ['rmb_dollar_exhange_rate', 'hs300'],
        primarySeriesIndex: 0,
        note: '人民币汇率中间价代理',
      },
    ],
  },
  {
    id: 'macro-usd-jpy',
    kind: 'macro',
    displayName: 'USD/JPY',
    metricMode: 'price',
    enabled: true,
    sourceHoldings: [],
    preferredMetrics: ['price'],
    proxyName: '美元兑日元',
    focusCodes: ['USD/JPY'],
    sources: [{ kind: 'yahoo_chart', symbol: 'USDJPY=X' }],
  },
  {
    id: 'macro-gold',
    kind: 'macro',
    displayName: '黄金',
    metricMode: 'price',
    enabled: true,
    sourceHoldings: [],
    preferredMetrics: ['price'],
    proxyName: '现货黄金(XAUUSD)',
    focusCodes: ['XAUUSD'],
    sources: [
      {
        kind: 'legulegu_aggregation',
        pageUrl: 'https://legulegu.com/stockdata/charts/1075',
        requestedDataKeys: ['us_dollar_index', 'xau_usd'],
        primarySeriesIndex: 1,
      },
    ],
  },
  {
    id: 'macro-wti',
    kind: 'macro',
    displayName: 'WTI 原油',
    metricMode: 'price',
    enabled: true,
    sourceHoldings: [],
    preferredMetrics: ['price'],
    proxyName: 'WTI 原油',
    focusCodes: ['WTI'],
    sources: [
      {
        kind: 'legulegu_aggregation',
        pageUrl: 'https://legulegu.com/stockdata/charts/771',
        requestedDataKeys: ['wti_service', 'xau_usd'],
        primarySeriesIndex: 0,
      },
    ],
  },
  {
    id: 'macro-brent',
    kind: 'macro',
    displayName: '布伦特原油',
    metricMode: 'price',
    enabled: true,
    sourceHoldings: [],
    preferredMetrics: ['price'],
    proxyName: 'Brent Crude Oil',
    focusCodes: ['BRENT'],
    sources: [{ kind: 'yahoo_chart', symbol: 'BZ=F' }],
  },
];
